#include "FileOption.h"
#include <map>
using namespace std;

FileOption::FileOption()
{
}


FileOption::~FileOption()
{
}


//读取.asc文件数据
void FileOption::ReadAscFile() 
{

}


//.asc文件转Pcd文件
void FileOption::AscToPcd()
{
	map<int, MyPoint>_mapPoint;
	string fileName = "D:\\vs2017projects\\Task2\\maptest.ply";
	ofstream OpenFile(fileName.c_str());
	OpenFile.precision(std::numeric_limits<double>::digits10);
	//ofstream OpenFile("D:\\vs2017projects\\Task2\\testmap.ply");
	if (OpenFile.fail())
	{
		cout << "打开文件错误!" << endl;
	}
	OpenFile << "# .PCD v0.7 - Point Cloud Data file format" << endl;
	OpenFile << "VERSION 0.7" << endl;
	OpenFile << "comment generated by platoply" << endl;
	OpenFile << "FIELDS x y z intensity" <<  endl;
	OpenFile << "SIZE 4 4 4 4" << endl;
	OpenFile << "TYPE F F F F" << endl;
	OpenFile << "COUNT 1 1 1 1" << endl;
	OpenFile << "VIEWPOINT 0 0 0 1 0 0 0" << endl;
	OpenFile << "WIDTH " << _mapPoint.size() << endl;
	OpenFile << "HEIGHT 1" << endl;
	OpenFile << "POINTS " << _mapPoint.size() << endl;
	OpenFile << "DATA ascii"<< endl;
	// 读取点的信息
	for (auto iter = _mapPoint.begin(); iter != _mapPoint.end(); iter++)
	{
		OpenFile << iter->first.x << " " << iter->first.y << " " << iter->first.z << endl;
	}
}


//把划分好的三角面片另存为.ply文件
void FileOption::SaveAsPLY() 
{

}

